package water_supply;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Bills extends javax.swing.JFrame {

    codes co = new codes();
    String id;
    String hn;

    public Bills() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        co.fillComboBox(cm1,"SELECT  concat(h.h_no,',', name) magac  FROM customer_homes ch, people p, homes h  WHERE p.people_no=ch.cus_no and h.h_no=ch.h_no", "magac");        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo4 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        txtser = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt3 = new RSMaterialComponent.RSTextFieldMaterial();
        txt1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel2 = new javax.swing.JLabel();
        cm1 = new RSMaterialComponent.RSComboBox();
        txt2 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dt1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconTwo1.setBackground(new java.awt.Color(255, 204, 102));
        rSButtonMaterialIconTwo1.setText("Clear");
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        jPanel3.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 110, 60));

        rSButtonMaterialIconTwo2.setBackground(new java.awt.Color(255, 204, 102));
        rSButtonMaterialIconTwo2.setText("Save");
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 110, 60));

        rSButtonMaterialIconTwo3.setBackground(new java.awt.Color(255, 204, 102));
        rSButtonMaterialIconTwo3.setText("Update");
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 110, 60));

        rSButtonMaterialIconTwo4.setBackground(new java.awt.Color(255, 204, 102));
        rSButtonMaterialIconTwo4.setText("Delete");
        rSButtonMaterialIconTwo4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconTwo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 110, 60));

        txtser.setBackground(new java.awt.Color(255, 204, 102));
        txtser.setPlaceholder("Search..");
        txtser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserActionPerformed(evt);
            }
        });
        jPanel3.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 210, 40));

        rSButtonIconTwo1.setBackground(new java.awt.Color(255, 204, 102));
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("House_Num:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bil_date:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 100, 30));

        txt3.setBackground(new java.awt.Color(255, 204, 102));
        txt3.setPhColor(new java.awt.Color(0, 0, 0));
        txt3.setPlaceholder("Enter Rate");
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        jPanel3.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 340, 50));

        txt1.setBackground(new java.awt.Color(255, 204, 102));
        txt1.setForeground(new java.awt.Color(255, 0, 0));
        txt1.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txt1.setPhColor(new java.awt.Color(0, 0, 0));
        txt1.setPlaceholder("Ex_rate");
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel3.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 320, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ex_rate:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 30));

        cm1.setBackground(new java.awt.Color(255, 204, 102));
        cm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cus_H Number" }));
        cm1.setColorArrow(new java.awt.Color(255, 204, 102));
        cm1.setColorFondo(new java.awt.Color(255, 204, 102));
        cm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm1ActionPerformed(evt);
            }
        });
        jPanel3.add(cm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 320, 50));

        txt2.setBackground(new java.awt.Color(255, 204, 102));
        txt2.setPhColor(new java.awt.Color(0, 0, 0));
        txt2.setPlaceholder("Cuurent_rate");
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        jPanel3.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 320, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current_rate:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rate:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 80, 30));
        jPanel3.add(dt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 442, 350, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 740, 630));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bills", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        // TODO add your handling code here:
        Date d1 = new Date(dt1.getDate().getTime());
        String oper = "insert";
        String sql = "call bills_pr('"+hn+"','"+ txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','" +d1+"','"+ oper + "',null)";
        co.setSql(sql);                  
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
        // TODO add your handling code here:
        Date d1 = new Date(dt1.getDate().getTime());
        String oper = "update";
        String sql = "call bills_pr('"+hn+"','"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+d1+"','"+oper+"','"+id+"')";
        co.setSql(sql);
    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    private void rSButtonMaterialIconTwo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo4ActionPerformed
        // TODO add your handling code here:
         Date d1 = new Date(dt1.getDate().getTime());
        if (JOptionPane.showConfirmDialog(null, "ma huptaa") == JOptionPane.YES_OPTION) {
            String oper = "delete";
            String sql = "call bills_pr('"+hn+"','"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+d1+"','"+oper+"','"+id+"')";
            co.setSql(sql);
        }
    }//GEN-LAST:event_rSButtonMaterialIconTwo4ActionPerformed

    private void txtserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
        // TODO add your handling code here:
        
        try {
            co.search("select b.b_no ,concat(h.h_no,',', name) magac,b.Ex_rate,Current_rate,rate,bil_date from bills b, people p, customer_homes ch, homes h where p.people_no=ch.cus_no and ch.cus_h_no=b.cus_H_no and h.h_no=ch.h_no and b_no='"+txtser.getText()+"'");
            if (co.rs.next()) {
                id = co.rs.getString("b_no");   
                cm1.setSelectedItem(co.rs.getString("magac"));
                txt1.setText(co.rs.getString("b.Ex_rate"));
                txt2.setText(co.rs.getString("Current_rate"));
                txt3.setText(co.rs.getString("rate"));
                dt1.setDate(co.rs.getDate("bil_date"));
            }
            else{
                JOptionPane.showMessageDialog(null, txtser.getText() + "not found");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    private void cm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm1ActionPerformed
        // TODO add your handling code here:
        String array[] = cm1.getSelectedItem().toString().split(",");
        hn = array[0];
    }//GEN-LAST:event_cm1ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBox cm1;
    private com.toedter.calendar.JDateChooser dt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo4;
    private RSMaterialComponent.RSTextFieldMaterial txt1;
    private RSMaterialComponent.RSTextFieldMaterial txt2;
    private RSMaterialComponent.RSTextFieldMaterial txt3;
    private RSMaterialComponent.RSTextFieldMaterial txtser;
    // End of variables declaration//GEN-END:variables
}
