package water_supply;
import java.sql.Date;
import javax.swing.JOptionPane;

public class Dash extends javax.swing.JFrame {

    codes co = new codes();
    String r_sin;
    String b_zone;
    String stat;
    String h_zone, com_bills_zone;

    public Dash() {
        initComponents();
        this.setLocationRelativeTo(this);
        co.fillComboBox(comprec, "select concat(t.rec_no,' ',p.name) mgc from receipt t, people p where t.people_no = p.people_no", "mgc");
        co.fillComboBox(cuscom, "SELECT concat(people_no,',',name) as cus from people p", "cus");
        co.fillComboBox(hcom1, "SELECT concat(h_no,',',owner,',', a.district,',',a.village,',',a.zone) as guryo from homes h , address a where h.add_no=a.add_no", "guryo");
        co.fillComboBox(com_b_zone, "SELECT concat(a.zone,'-',p1.name,'-',p2.name,'-',s.ser_name) as zone from address a,homes h,customer_homes ch,people p1,people p2,services s where a.add_no=h.add_no and h.h_no=ch.h_no and p1.people_no=ch.cus_no and p2.people_no=h.owner and s.ser_no=ch.ser_no ORDER by a.zone", "zone");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSButtonMaterialIconOne5 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rg = new RSMaterialComponent.RSButtonMaterialIconOne();
        rc = new RSMaterialComponent.RSButtonMaterialIconOne();
        fnn = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSPanelMaterial3 = new RSMaterialComponent.RSPanelMaterial();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        Main = new javax.swing.JTabbedPane();
        panal1 = new javax.swing.JPanel();
        rSLabelImage2 = new necesario.RSLabelImage();
        panal2 = new javax.swing.JPanel();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo4 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo8 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSLabelImage1 = new necesario.RSLabelImage();
        panal3 = new javax.swing.JPanel();
        rSButtonMaterialIconTwo5 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSLabelImage3 = new necesario.RSLabelImage();
        panal4 = new javax.swing.JPanel();
        rSButtonMaterialIconTwo7 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo6 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSLabelImage4 = new necesario.RSLabelImage();
        panal5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comprec = new RSMaterialComponent.RSComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        rd1 = new com.toedter.calendar.JDateChooser();
        rd2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        bd1 = new com.toedter.calendar.JDateChooser();
        bd2 = new com.toedter.calendar.JDateChooser();
        com_b_zone = new RSMaterialComponent.RSComboBox();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        chd1 = new com.toedter.calendar.JDateChooser();
        chd2 = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        hcom1 = new RSMaterialComponent.RSComboBox();
        jPanel8 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        hcom2 = new RSMaterialComponent.RSComboBox();
        jPanel9 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        hcom3 = new RSMaterialComponent.RSComboBox();
        jPanel10 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        hcom4 = new RSMaterialComponent.RSComboBox();
        jPanel11 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        hcom6 = new RSMaterialComponent.RSComboBox();
        jPanel13 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        hcom7 = new RSMaterialComponent.RSComboBox();
        jPanel14 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        hcom8 = new RSMaterialComponent.RSComboBox();
        cuscom = new RSMaterialComponent.RSComboBox();
        jPanel15 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        hcom9 = new RSMaterialComponent.RSComboBox();
        jPanel17 = new javax.swing.JPanel();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        hcom10 = new RSMaterialComponent.RSComboBox();
        jPanel18 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        hcom11 = new RSMaterialComponent.RSComboBox();
        cuscom1 = new RSMaterialComponent.RSComboBox();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial1.setBackground(new java.awt.Color(0, 153, 204));
        rSPanelMaterial1.setIntensity(5);
        rSPanelMaterial1.setShadowBottom(false);
        rSPanelMaterial1.setShadowLeft(false);
        rSPanelMaterial1.setShadowTop(false);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconOne5.setBackground(new java.awt.Color(0, 153, 204));
        rSButtonMaterialIconOne5.setForeground(new java.awt.Color(204, 255, 204));
        rSButtonMaterialIconOne5.setText("Home");
        rSButtonMaterialIconOne5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonMaterialIconOne5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        rSButtonMaterialIconOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne5ActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(rSButtonMaterialIconOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 290, 50));

        rg.setBackground(new java.awt.Color(0, 153, 204));
        rg.setText("Registration");
        rg.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rg.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RATE_REVIEW);
        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 290, 50));

        rc.setBackground(new java.awt.Color(0, 153, 204));
        rc.setText("Reception");
        rc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rc.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RECEIPT);
        rc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(rc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 290, 50));

        fnn.setBackground(new java.awt.Color(0, 153, 204));
        fnn.setText("Financial");
        fnn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        fnn.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BALANCE);
        fnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnnActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(fnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 290, 50));

        rSButtonMaterialIconOne2.setBackground(new java.awt.Color(0, 153, 204));
        rSButtonMaterialIconOne2.setText("Report");
        rSButtonMaterialIconOne2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonMaterialIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REPORT);
        rSButtonMaterialIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne2ActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(rSButtonMaterialIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, 50));

        rSButtonMaterialIconOne1.setBackground(new java.awt.Color(0, 153, 204));
        rSButtonMaterialIconOne1.setText("LogOut");
        rSButtonMaterialIconOne1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonMaterialIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        rSButtonMaterialIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne1ActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(rSButtonMaterialIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 290, 50));

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 330, 1240));

        rSPanelMaterial3.setIntensity(5);
        rSPanelMaterial3.setShadowBottom(false);
        rSPanelMaterial3.setShadowTop(false);
        rSPanelMaterial3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon2.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon2.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon2.setText("Water Supply System");
        rSLabelTextIcon2.setFont(new java.awt.Font("Times New Roman", 1, 110)); // NOI18N
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FAVORITE);
        rSPanelMaterial3.add(rSLabelTextIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 1600, 160));
        rSLabelTextIcon2.getAccessibleContext().setAccessibleName("Water Supply  System");

        getContentPane().add(rSPanelMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1910, 210));

        panal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water_supply/water2.jpg"))); // NOI18N
        panal1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1570, 1240));

        Main.addTab("tab1", panal1);

        panal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconTwo2.setText("Address");
        rSButtonMaterialIconTwo2.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        panal2.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, 50));

        rSButtonMaterialIconTwo3.setText("people");
        rSButtonMaterialIconTwo3.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });
        panal2.add(rSButtonMaterialIconTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 50));

        rSButtonMaterialIconTwo4.setText("Homes");
        rSButtonMaterialIconTwo4.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        rSButtonMaterialIconTwo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo4ActionPerformed(evt);
            }
        });
        panal2.add(rSButtonMaterialIconTwo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, 50));

        rSButtonMaterialIconTwo8.setText("Customer_homes");
        rSButtonMaterialIconTwo8.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        rSButtonMaterialIconTwo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo8ActionPerformed(evt);
            }
        });
        panal2.add(rSButtonMaterialIconTwo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 240, 50));

        rSButtonMaterialIconTwo1.setText("Service");
        rSButtonMaterialIconTwo1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_SHOPPING_CART);
        rSButtonMaterialIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo1ActionPerformed(evt);
            }
        });
        panal2.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 240, 50));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water_supply/rr.jpg"))); // NOI18N
        panal2.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 1300));

        Main.addTab("tab2", panal2);

        panal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconTwo5.setText("Receipt");
        rSButtonMaterialIconTwo5.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RECEIPT);
        rSButtonMaterialIconTwo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo5ActionPerformed(evt);
            }
        });
        panal3.add(rSButtonMaterialIconTwo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, 50));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water_supply/recept.png"))); // NOI18N
        panal3.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 1300));

        Main.addTab("tab3", panal3);

        panal4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconTwo7.setText("Bills");
        rSButtonMaterialIconTwo7.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ATTACH_MONEY);
        rSButtonMaterialIconTwo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo7ActionPerformed(evt);
            }
        });
        panal4.add(rSButtonMaterialIconTwo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 230, 50));

        rSButtonMaterialIconTwo6.setText("Accounts");
        rSButtonMaterialIconTwo6.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_BALANCE);
        rSButtonMaterialIconTwo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo6ActionPerformed(evt);
            }
        });
        panal4.add(rSButtonMaterialIconTwo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 230, 50));

        rSLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water_supply/fnnce.jpg"))); // NOI18N
        panal4.add(rSLabelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 1300));

        Main.addTab("tab4", panal4);

        panal5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receipt Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Single");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 30));

        jButton2.setText("All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        comprec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Receipt" }));
        comprec.setColorArrow(new java.awt.Color(51, 153, 255));
        comprec.setColorFondo(new java.awt.Color(51, 153, 255));
        comprec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprecActionPerformed(evt);
            }
        });
        jPanel1.add(comprec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        panal5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 270, 210));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receipt Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 80, 30));
        jPanel2.add(rd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 180, -1));
        jPanel2.add(rd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, -1));

        panal5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 280, 220));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bills Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, -1));
        jPanel3.add(bd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, -1));
        jPanel3.add(bd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, -1));

        com_b_zone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select BIll Zone" }));
        com_b_zone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_b_zoneActionPerformed(evt);
            }
        });
        jPanel3.add(com_b_zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, -1));

        jButton4.setText("Single");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        panal5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 290, 230));

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Homes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("All");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 172, 70, -1));

        jButton12.setText("Bet");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 70, -1));
        jPanel7.add(chd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));
        jPanel7.add(chd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        panal5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 260, 220));

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("Zone");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton10.setText("All");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom1ActionPerformed(evt);
            }
        });
        jPanel6.add(hcom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setText("Zone");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton14.setText("All");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom2ActionPerformed(evt);
            }
        });
        jPanel8.add(hcom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 210));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setText("Zone");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton16.setText("All");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom3ActionPerformed(evt);
            }
        });
        jPanel9.add(hcom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setText("Zone");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton18.setText("All");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom4ActionPerformed(evt);
            }
        });
        jPanel10.add(hcom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 210));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 280, 210));

        panal5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 280, 210));

        jPanel11.setBackground(new java.awt.Color(255, 102, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Statement", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setText("Single");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, -1));

        jPanel12.setBackground(new java.awt.Color(0, 153, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setText("Zone");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton22.setText("All");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom6ActionPerformed(evt);
            }
        });
        jPanel12.add(hcom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 210));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton23.setText("Zone");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton24.setText("All");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom7ActionPerformed(evt);
            }
        });
        jPanel13.add(hcom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton25.setText("Zone");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton26.setText("All");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom8ActionPerformed(evt);
            }
        });
        jPanel14.add(hcom8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 210));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 280, 210));

        cuscom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Customer" }));
        cuscom.setColorArrow(new java.awt.Color(255, 102, 255));
        cuscom.setColorBorde(new java.awt.Color(255, 102, 255));
        cuscom.setColorFondo(new java.awt.Color(255, 102, 255));
        cuscom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuscomActionPerformed(evt);
            }
        });
        jPanel11.add(cuscom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 102, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Statement", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton27.setText("Single");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, -1));

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton28.setText("Zone");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton29.setText("All");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom9ActionPerformed(evt);
            }
        });
        jPanel16.add(hcom9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 210));

        jPanel17.setBackground(new java.awt.Color(0, 153, 153));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton30.setText("Zone");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton31.setText("All");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom10ActionPerformed(evt);
            }
        });
        jPanel17.add(hcom10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel18.setBackground(new java.awt.Color(0, 153, 153));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton32.setText("Zone");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        jButton33.setText("All");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 152, 70, -1));

        hcom11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Homes" }));
        hcom11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcom11ActionPerformed(evt);
            }
        });
        jPanel18.add(hcom11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 210));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 280, 210));

        cuscom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Customer" }));
        cuscom1.setColorArrow(new java.awt.Color(255, 102, 255));
        cuscom1.setColorBorde(new java.awt.Color(255, 102, 255));
        cuscom1.setColorFondo(new java.awt.Color(255, 102, 255));
        cuscom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuscom1ActionPerformed(evt);
            }
        });
        jPanel15.add(cuscom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 280, 210));

        panal5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 280, 210));

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "get_customer_homes_stats", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Get");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, 30));

        panal5.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 150, 260, 190));

        Main.addTab("Report", panal5);

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 1580, 1300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne5ActionPerformed
        // TODO add your handling code here:
        Main.setSelectedComponent(panal1);
    }//GEN-LAST:event_rSButtonMaterialIconOne5ActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        Main.setSelectedComponent(panal2);
    }//GEN-LAST:event_rgActionPerformed

    private void rcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcActionPerformed
        Main.setSelectedComponent(panal3);
    }//GEN-LAST:event_rcActionPerformed

    private void fnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnnActionPerformed
        Main.setSelectedComponent(panal4);
    }//GEN-LAST:event_fnnActionPerformed

    private void rSButtonMaterialIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne2ActionPerformed
        Main.setSelectedComponent(panal5);
    }//GEN-LAST:event_rSButtonMaterialIconOne2ActionPerformed

    private void rSButtonMaterialIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne1ActionPerformed
        Login_Form f = new Login_Form();
        f.show();
    }//GEN-LAST:event_rSButtonMaterialIconOne1ActionPerformed

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        Addresstable a = new Addresstable();
        a.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
        PeopleTable p = new PeopleTable();
        p.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    private void rSButtonMaterialIconTwo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo4ActionPerformed
        HomesTable ht = new HomesTable();
        ht.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo4ActionPerformed

    private void rSButtonMaterialIconTwo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo8ActionPerformed
        CustomerHomesTable ch = new CustomerHomesTable();
        ch.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo8ActionPerformed

    private void rSButtonMaterialIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo1ActionPerformed
        ServiceTable s = new ServiceTable();
        s.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo1ActionPerformed

    private void rSButtonMaterialIconTwo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo5ActionPerformed
        // TODO add your handling code here:
        ReceiptTable r = new ReceiptTable();
        r.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo5ActionPerformed

    private void rSButtonMaterialIconTwo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo7ActionPerformed
        // TODO add your handling code here:
        BillsTable b = new BillsTable();
        b.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo7ActionPerformed

    private void rSButtonMaterialIconTwo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo6ActionPerformed
        // TODO add your handling code here:
        Accountstable ac = new Accountstable();
        ac.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconTwo6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        co.report("src\\water_supply\\receipt_sin.jrxml", "call receipt_sin('" + r_sin + "')");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        co.report("src\\water_supply\\receipt_all.jrxml", "call receipt_all()");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comprecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprecActionPerformed
        String array[] = comprec.getSelectedItem().toString().split(" ");
        r_sin = array[0];
    }//GEN-LAST:event_comprecActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Date d1 = new Date(rd1.getDate().getTime());
        Date d2 = new Date(rd2.getDate().getTime());
        co.report("src\\water_supply\\receipt_bet.jrxml", "call receipt_bet('" + d1 + "','" + d2 + "')");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        co.report("src\\water_supply\\Bills_all.jrxml", "call bills_all()");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void com_b_zoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_b_zoneActionPerformed
        // TODO add your handling code here:
        String array[] = com_b_zone.getSelectedItem().toString().split("-");
        com_bills_zone = array[0];
    }//GEN-LAST:event_com_b_zoneActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Date d1 = new Date(bd1.getDate().getTime());
        Date d2 = new Date(bd2.getDate().getTime());
//        String sql = "call bills_zone('" + d1 + "','" + d2 + "','" + com_bills_zone + "')";
//        JOptionPane.showMessageDialog(null, sql);
        co.report("src\\water_supply\\bills_zone.jrxml", "call bills_zone('" + d1 + "','" + d2 + "','" + com_bills_zone + "')");
//        String sql ="call bills_zone('" + d1 + "','" + d2 + "','" + com_bills_zone + "')"
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        co.report("src\\water_supply\\customer_homes_all.jrxml", "call customer_homes_all()");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Date dt1 = new Date(chd1.getDate().getTime());
        Date dt2 = new Date(chd2.getDate().getTime());
        co.report("src\\water_supply\\customer_homes_bet.jrxml", "call customer_homes_bet('" + dt1 + "','" + dt2 + "')");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        co.report("src\\water_supply\\home_rep_byzone.jrxml", "home_rep_byzone(('" + h_zone + "')");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        co.report("src\\water_supply\\homes_all.jrxml", "call homes_all()");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void hcom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom1ActionPerformed
        String array[] = hcom1.getSelectedItem().toString().split(",");
        h_zone = array[0];
    }//GEN-LAST:event_hcom1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void hcom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void hcom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void hcom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom4ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        co.report("src\\water_supply\\statement_c.jrxml", "call statement_c('" + stat + "')");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void hcom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom6ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void hcom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom7ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void hcom8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom8ActionPerformed

    private void cuscomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuscomActionPerformed
        String array[] = cuscom.getSelectedItem().toString().split(",");
        stat = array[0];
    }//GEN-LAST:event_cuscomActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void hcom9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom9ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void hcom10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom10ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void hcom11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcom11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcom11ActionPerformed

    private void cuscom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuscom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuscom1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        co.report("src\\water_supply\\get_customer_homes_stats.jrxml", "call get_customer_homes_stats()");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Main;
    private com.toedter.calendar.JDateChooser bd1;
    private com.toedter.calendar.JDateChooser bd2;
    private com.toedter.calendar.JDateChooser chd1;
    private com.toedter.calendar.JDateChooser chd2;
    private RSMaterialComponent.RSComboBox com_b_zone;
    private RSMaterialComponent.RSComboBox comprec;
    private RSMaterialComponent.RSComboBox cuscom;
    private RSMaterialComponent.RSComboBox cuscom1;
    public RSMaterialComponent.RSButtonMaterialIconOne fnn;
    private RSMaterialComponent.RSComboBox hcom1;
    private RSMaterialComponent.RSComboBox hcom10;
    private RSMaterialComponent.RSComboBox hcom11;
    private RSMaterialComponent.RSComboBox hcom2;
    private RSMaterialComponent.RSComboBox hcom3;
    private RSMaterialComponent.RSComboBox hcom4;
    private RSMaterialComponent.RSComboBox hcom6;
    private RSMaterialComponent.RSComboBox hcom7;
    private RSMaterialComponent.RSComboBox hcom8;
    private RSMaterialComponent.RSComboBox hcom9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel panal1;
    private javax.swing.JPanel panal2;
    private javax.swing.JPanel panal3;
    private javax.swing.JPanel panal4;
    private javax.swing.JPanel panal5;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne5;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo4;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo5;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo6;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo7;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo8;
    private necesario.RSLabelImage rSLabelImage1;
    private necesario.RSLabelImage rSLabelImage2;
    private necesario.RSLabelImage rSLabelImage3;
    private necesario.RSLabelImage rSLabelImage4;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial3;
    public RSMaterialComponent.RSButtonMaterialIconOne rc;
    private com.toedter.calendar.JDateChooser rd1;
    private com.toedter.calendar.JDateChooser rd2;
    public RSMaterialComponent.RSButtonMaterialIconOne rg;
    // End of variables declaration//GEN-END:variables
}
