package water_supply;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Homes extends javax.swing.JFrame {

    codes co = new codes();
    String id;
    String ownr;
    String ad_n;

    public Homes() {
        initComponents();
        this.setLocationRelativeTo(this);
         this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        co.fillComboBox(cmp1, "select concat(people_no,',',name) as dad from people p ORDER by p.people_no", "dad");
        co.fillComboBox(cmp2, "select concat( add_no,',',district,',',zone) as a from address", "a");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo4 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        txtser = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        cmp2 = new RSMaterialComponent.RSComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmp1 = new RSMaterialComponent.RSComboBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconTwo1.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonMaterialIconTwo1.setText("Clear");
        rSButtonMaterialIconTwo1.setBackgroundHover(new java.awt.Color(0, 102, 102));
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        jPanel3.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 110, 60));

        rSButtonMaterialIconTwo2.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonMaterialIconTwo2.setText("Save");
        rSButtonMaterialIconTwo2.setBackgroundHover(new java.awt.Color(0, 102, 102));
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 60));

        rSButtonMaterialIconTwo3.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonMaterialIconTwo3.setText("Update");
        rSButtonMaterialIconTwo3.setBackgroundHover(new java.awt.Color(0, 102, 102));
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 110, 60));

        rSButtonMaterialIconTwo4.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonMaterialIconTwo4.setText("Delete");
        rSButtonMaterialIconTwo4.setBackgroundHover(new java.awt.Color(0, 102, 102));
        rSButtonMaterialIconTwo4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconTwo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 110, 60));

        txtser.setBackground(new java.awt.Color(153, 0, 153));
        txtser.setForeground(new java.awt.Color(255, 255, 255));
        txtser.setColorMaterial(new java.awt.Color(0, 0, 255));
        txtser.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtser.setPhColor(new java.awt.Color(255, 255, 255));
        txtser.setPlaceholder("Search..");
        txtser.setSelectionColor(new java.awt.Color(0, 102, 102));
        txtser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserActionPerformed(evt);
            }
        });
        jPanel3.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 210, 40));

        rSButtonIconTwo1.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        cmp2.setBackground(new java.awt.Color(153, 0, 153));
        cmp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add Number" }));
        cmp2.setColorArrow(new java.awt.Color(153, 0, 153));
        cmp2.setColorFondo(new java.awt.Color(153, 0, 153));
        cmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 310, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add_Num:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Owner:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 30));

        cmp1.setBackground(new java.awt.Color(153, 0, 153));
        cmp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enter Owner" }));
        cmp1.setColorArrow(new java.awt.Color(153, 0, 153));
        cmp1.setColorFondo(new java.awt.Color(153, 0, 153));
        cmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp1ActionPerformed(evt);
            }
        });
        jPanel3.add(cmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 320, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 660, 420));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Homes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        // TODO add your handling code here:
        String oper = "insert";
        String sql = "call homes_pr('"+ownr+"','"+ad_n+"','"+oper+"',null)";
        co.setSql(sql);
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
        // TODO add your handling code here:
        String oper = "update";
        String sql = "call homes_pr('"+ownr+"','"+ad_n+"','"+oper+"','"+id+"')";
        co.setSql(sql);
    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    private void rSButtonMaterialIconTwo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo4ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "ma huptaa") == JOptionPane.YES_OPTION) {
            String oper = "delete";
            String sql = "call homes_pr('"+ownr+"','"+ad_n+"','"+oper+"','"+id+"')";
            co.setSql(sql);
        }
    }//GEN-LAST:event_rSButtonMaterialIconTwo4ActionPerformed

    private void cmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp2ActionPerformed
        // TODO add your handling code here:
        String array[] = cmp2.getSelectedItem().toString().split(",");
        ad_n = array[0];
    }//GEN-LAST:event_cmp2ActionPerformed

    private void cmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp1ActionPerformed
        // TODO add your handling code here:
        String array[] = cmp1.getSelectedItem().toString().split(",");
        ownr = array[0];
    }//GEN-LAST:event_cmp1ActionPerformed

    private void txtserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
        try {
            co.search("select h_no,concat(people_no,',',name) ow,concat(a.add_no,',',district,',',zone) addrs from people p, address a, homes h where a.add_no=h.add_no and p.people_no=h.owner and h.h_no='"+txtser.getText()+"'");

            if (co.rs.next()) {
                id = co.rs.getString("h_no");
                cmp1.setSelectedItem(co.rs.getString("ow"));
                cmp2.setSelectedItem(co.rs.getString("addrs"));
                

            } else {
                JOptionPane.showMessageDialog(null, "Xogtan " + txtser.getText() + " lama helin.");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Qalad ayaa jira: " + ex.getMessage());
        }
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBox cmp1;
    private RSMaterialComponent.RSComboBox cmp2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo4;
    private RSMaterialComponent.RSTextFieldMaterial txtser;
    // End of variables declaration//GEN-END:variables
}
