package water_supply;

import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Receipt extends javax.swing.JFrame {

    codes co = new codes();
    String id;
    String pn;
    String acc_n;

    public Receipt() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        co.fillComboBox(cmp1, "SELECT " + "concat( p.people_no, ',',p.name) as dad from people p", "dad");
        co.fillComboBox(cmp2, "SELECT concat(a.acc_no,' ,' ,a.acc_name) as akon  from accounts a", "akon");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtser = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo4 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        dt1 = new com.toedter.calendar.JDateChooser();
        cmp2 = new RSMaterialComponent.RSComboBox();
        cmp1 = new RSMaterialComponent.RSComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt2 = new RSMaterialComponent.RSTextFieldMaterial();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 0, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtser.setBackground(new java.awt.Color(153, 0, 255));
        txtser.setForeground(new java.awt.Color(255, 255, 255));
        txtser.setColorMaterial(new java.awt.Color(255, 255, 255));
        txtser.setPhColor(new java.awt.Color(255, 255, 255));
        txtser.setPlaceholder("Enter Amount");
        txtser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserActionPerformed(evt);
            }
        });
        jPanel3.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 230, 51));

        rSButtonMaterialIconTwo1.setBackground(new java.awt.Color(153, 0, 255));
        rSButtonMaterialIconTwo1.setText("Clear");
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        jPanel3.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 110, 60));

        rSButtonMaterialIconTwo2.setBackground(new java.awt.Color(153, 0, 255));
        rSButtonMaterialIconTwo2.setText("Save");
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 110, 60));

        rSButtonMaterialIconTwo3.setBackground(new java.awt.Color(153, 0, 255));
        rSButtonMaterialIconTwo3.setText("Update");
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 110, 60));

        rSButtonMaterialIconTwo4.setBackground(new java.awt.Color(153, 0, 255));
        rSButtonMaterialIconTwo4.setText("Delete");
        rSButtonMaterialIconTwo4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconTwo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialIconTwo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 110, 60));

        rSButtonIconTwo1.setBackground(new java.awt.Color(153, 0, 255));
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));
        jPanel3.add(dt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 290, 40));

        cmp2.setBackground(new java.awt.Color(102, 102, 255));
        cmp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selector your acc number" }));
        cmp2.setColorArrow(new java.awt.Color(153, 0, 255));
        cmp2.setColorFondo(new java.awt.Color(153, 0, 255));
        cmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp2ActionPerformed(evt);
            }
        });
        jPanel3.add(cmp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 290, 50));

        cmp1.setBackground(new java.awt.Color(153, 0, 255));
        cmp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selector your people number" }));
        cmp1.setColorArrow(new java.awt.Color(153, 0, 255));
        cmp1.setColorFondo(new java.awt.Color(153, 0, 255));
        cmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmp1ActionPerformed(evt);
            }
        });
        jPanel3.add(cmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("People_num: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amount:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 90, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Acc_number: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 160, 30));

        txt2.setBackground(new java.awt.Color(153, 0, 255));
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt2.setPhColor(new java.awt.Color(255, 255, 255));
        txt2.setPlaceholder("Enter Amount");
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        jPanel3.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 280, 51));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 770, 590));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receipt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserActionPerformed

    private void rSButtonMaterialIconTwo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo4ActionPerformed
        Date d1 = new Date(dt1.getDate().getTime());
        if (JOptionPane.showConfirmDialog(null, "ma huptaa") == JOptionPane.YES_OPTION) {
            String oper = "delete";
            String sql = "call receipt_pr('" + pn + "','" + txt2.getText() + "','" + d1 + "','" + acc_n + "', '" + oper + "','" + id + "')";
            co.setSql(sql);
        }
    }//GEN-LAST:event_rSButtonMaterialIconTwo4ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
        // TODO add your handling code here:
        Date d1 = new Date(dt1.getDate().getTime());
        String oper = "update";
        String sql = "call receipt_pr('" + pn + "','" + txt2.getText() + "','" + d1 + "', '" + acc_n + "', '" + oper + "','" + id + "')";
        co.setSql(sql);
    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        // TODO add your handling code here:
        Date d1 = new Date(dt1.getDate().getTime());
        String oper = "insert";
        String sql = "call receipt_pr('" + pn + "', '" + txt2.getText() + "', '" + d1 + "', '" + acc_n + "', '" + oper + "',null)";
        co.setSql(sql);
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
        // TODO add your handling code here:
        try {
            co.search("select rec_no, concat(p.people_no, ',',p.name) as p, amount,rec_Date, concat(a.acc_no,' ,' ,a.acc_name) as a from receipt rc, people p ,accounts a where rc.rec_no = p.people_no and rc.rec_no=a.Acc_no and rc.rec_no='" + txtser.getText() + "'");

            if (co.rs.next()) {
                id = co.rs.getString("rec_no");
                cmp1.setSelectedItem(co.rs.getString("p"));
                dt1.setDate(co.rs.getDate("rec_Date"));
                txt2.setText(co.rs.getString("amount"));
                cmp2.setSelectedItem(co.rs.getString("a"));

            } else {
                JOptionPane.showMessageDialog(null, "Xogtan " + txtser.getText() + " lama helin.");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Qalad ayaa jira: " + ex.getMessage());
        }
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    private void cmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp2ActionPerformed
        // TODO add your handling code here:
        String array[] = cmp2.getSelectedItem().toString().split(",");
        acc_n = array[0];
    }//GEN-LAST:event_cmp2ActionPerformed

    private void cmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmp1ActionPerformed
        // TODO add your handling code here:
        String array[] = cmp1.getSelectedItem().toString().split(",");
        pn = array[0];
    }//GEN-LAST:event_cmp1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBox cmp1;
    private RSMaterialComponent.RSComboBox cmp2;
    private com.toedter.calendar.JDateChooser dt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo4;
    private RSMaterialComponent.RSTextFieldMaterial txt2;
    private RSMaterialComponent.RSTextFieldMaterial txtser;
    // End of variables declaration//GEN-END:variables
}
